spring:
  application:
    name: carcare
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Skopje
  jackson:
    time-zone: Europe/Skopje
  flyway:
    enabled: true
  thymeleaf:
    check-template-location: false
app:
  time-zone: Europe/Skopje
  jwt:
    secret: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    access-minutes: 15
    refresh-days: 30
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
