ALTER TABLE offers
    ADD COLUMN IF NOT EXISTS subtotal_amount NUMERIC(12,2) DEFAULT 0 NOT NULL;

ALTER TABLE offers
    ADD COLUMN IF NOT EXISTS discount_percent NUMERIC(5,2) DEFAULT 0 NOT NULL;

ALTER TABLE offers
    ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(12,2) DEFAULT 0 NOT NULL;