ALTER TABLE roles ADD COLUMN IF NOT EXISTS created_by VARCHAR(160);
ALTER TABLE roles ADD COLUMN IF NOT EXISTS updated_by VARCHAR(160);

ALTER TABLE app_users ADD COLUMN IF NOT EXISTS created_by VARCHAR(160);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS updated_by VARCHAR(160);

ALTER TABLE employees ADD COLUMN IF NOT EXISTS created_by VARCHAR(160);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS updated_by VARCHAR(160);

ALTER TABLE customers ADD COLUMN IF NOT EXISTS created_by VARCHAR(160);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS updated_by VARCHAR(160);

ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS created_by VARCHAR(160);
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS updated_by VARCHAR(160);

ALTER TABLE appointments ADD COLUMN IF NOT EXISTS created_by VARCHAR(160);
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS updated_by VARCHAR(160);

ALTER TABLE service_records ADD COLUMN IF NOT EXISTS created_by VARCHAR(160);
ALTER TABLE service_records ADD COLUMN IF NOT EXISTS updated_by VARCHAR(160);

ALTER TABLE offers ADD COLUMN IF NOT EXISTS created_by VARCHAR(160);
ALTER TABLE offers ADD COLUMN IF NOT EXISTS updated_by VARCHAR(160);

ALTER TABLE offer_parts ADD COLUMN IF NOT EXISTS created_by VARCHAR(160);
ALTER TABLE offer_parts ADD COLUMN IF NOT EXISTS updated_by VARCHAR(160);

ALTER TABLE service_documents ADD COLUMN IF NOT EXISTS created_by VARCHAR(160);
ALTER TABLE service_documents ADD COLUMN IF NOT EXISTS updated_by VARCHAR(160);

ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS created_by VARCHAR(160);
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS updated_by VARCHAR(160);

ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS created_by VARCHAR(160);
ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS updated_by VARCHAR(160);
